format_version: 10
pipelines:
  my_pipeline:
    group: my_group
    label_template: "${git[:7]}"
    materials:
      git:
        git: "https://github.com/my-org/my-repo.git"
        branch: master
    stages:
      - build:
          jobs:
            build:
              tasks:
               - exec:
                   command: ./build.sh
      - test:
          jobs:
            test:
              tasks:
               - exec:
                   command: ./test.sh
