format_version: 10
pipelines:
  my_pipeline:
    group: defaultGroup
    label_template: "${git[:7]}"
    materials:
      git:
        git: https://github.com/miewone/myfirstgocd
        username: dlsrk489@gmail.com
        shallow_clone: false
        auto_update: true
        branch: main
        encrypted_password: AES:5sUlXe66lzHA9oTWBKhE6Q==:lPPFwSHOmcBnLBNYTwi8Oei4PyDa/Sy8f23bn94XJx8tsY6wt5CknPSECNEPux/k
    stages:
      - build:
          jobs:
            build:
              tasks:
               - exec:
                   command: ./build.sh
      - test:
          jobs:
            test:
              tasks:
               - exec:
                   command: ./test.sh
      - deploy:
          jobs:
            deploy:
              tasks:
               - exec:
                   command: ./deploy.sh
