---
name : CI
on:
  push:
    branches:
     - main
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Grant execute permission for script
        run: chmod +x ./.github/validate.sh

      - name: Validate
        run: ./.github/validate.sh
      
      - name: Commit and push if changed
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          if [[ $(git diff --cached | wc -l) -gt 0 ]]; then
            git commit -m "Add pipeline"
            git remote set-url origin https://x-access-token:${{ secrets.CI_GITHUB_TOKEN }}@github.com/${{ github.repository }}
            git push
          fi